(defparameter cores 4)
(defparameter maxsum 2000000000)
(setf maxsum (/ maxsum cores))

(let ((sum 0))
	(do((n 0 (1+ n))) ((<= cores n)) (let ((esum 0))
		(do((i 0 (1+ i))) ((<= maxsum i))
			(incf esum)
		)
		(incf sum esum)
	))
	(format t "~d~%" sum)
)
